package npm

import (
	"context"
	"encoding/json"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"rootio_patcher/cmd/rootio_patcher/common"
	"rootio_patcher/pkg/rootio"
)

// TestNpmApp_UpdatePackageJSON_Npm tests npm overrides format
func TestNpmApp_UpdatePackageJSON_Npm(t *testing.T) {
	ctx := context.Background()
	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))

	// Create temp directory
	tmpDir := t.TempDir()

	// Create package.json
	packageJSON := filepath.Join(tmpDir, "package.json")
	initialContent := `{
  "name": "test-project",
  "version": "1.0.0",
  "dependencies": {
    "lodash": "4.17.20"
  }
}`
	if err := os.WriteFile(packageJSON, []byte(initialContent), 0644); err != nil {
		t.Fatalf("Failed to create package.json: %v", err)
	}

	// Change to temp directory
	originalDir, _ := os.Getwd()
	defer os.Chdir(originalDir)
	os.Chdir(tmpDir)

	// Create app with mock services
	mockAPIClient := &MockAPIClient{
		AnalyzePackagesFunc: func(ctx context.Context, packages []rootio.Package, ignore []rootio.Package, ecosystem string) (*rootio.AnalyzePackagesResponse, error) {
			return &rootio.AnalyzePackagesResponse{
				Patches: []rootio.PackagePatch{
					{
						PackageName: "lodash",
						Version:     "4.17.20",
						Patch:       rootio.PatchInfo{Name: "lodash", Version: "4.17.21-root.io.1"},
						PatchAlias:  rootio.PatchInfo{Name: "@rootio/lodash", Version: "4.17.21-root.io.1"},
					},
				},
			}, nil
		},
	}

	// Create a fake lock file
	lockFile := filepath.Join(tmpDir, "package-lock.json")
	lockContent := `{
  "name": "test-project",
  "lockfileVersion": 3,
  "packages": {
    "": {
      "dependencies": { "lodash": "4.17.20" }
    },
    "node_modules/lodash": {
      "version": "4.17.20"
    }
  }
}`
	if err := os.WriteFile(lockFile, []byte(lockContent), 0644); err != nil {
		t.Fatalf("Failed to create lock file: %v", err)
	}

	app := NewAppWithServices(
		"test-key",
		"https://api.root.io",
		"npm",
		false, // not dry-run
		nil,
		logger,
		NewParser(),
		mockAPIClient,
	)

	// Run the app
	if err := app.Run(ctx); err != nil {
		t.Fatalf("App run failed: %v", err)
	}

	// Read updated package.json
	updatedContent, err := os.ReadFile(packageJSON)
	if err != nil {
		t.Fatalf("Failed to read updated package.json: %v", err)
	}

	// Parse and verify
	var pkgJSON map[string]interface{}
	if err := json.Unmarshal(updatedContent, &pkgJSON); err != nil {
		t.Fatalf("Failed to parse updated package.json: %v", err)
	}

	// lodash@4.17.20 is the user's direct dep AT the vulnerable version,
	// and no transitive consumer exists. Expected result: the dependency
	// entry is bumped in place (no aliasing, no name change).
	deps := pkgJSON["dependencies"].(map[string]interface{})

	expectedVersion := "4.17.21-root.io.1"
	if deps["lodash"] == nil {
		t.Fatal("Expected lodash to remain in dependencies")
	} else if deps["lodash"].(string) != expectedVersion {
		t.Errorf("Expected lodash version %q, got %q", expectedVersion, deps["lodash"])
	}

	t.Log("Successfully bumped direct dep in place for npm (no transitive consumers)")
}

// TestNpmApp_UpdatePackageJSON_Yarn tests yarn resolutions format
func TestNpmApp_UpdatePackageJSON_Yarn(t *testing.T) {
	ctx := context.Background()
	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))

	// Create temp directory
	tmpDir := t.TempDir()

	// Create package.json
	packageJSON := filepath.Join(tmpDir, "package.json")
	initialContent := `{
  "name": "test-project",
  "version": "1.0.0",
  "dependencies": {
    "express": "4.18.0"
  }
}`
	if err := os.WriteFile(packageJSON, []byte(initialContent), 0644); err != nil {
		t.Fatalf("Failed to create package.json: %v", err)
	}

	// Change to temp directory
	originalDir, _ := os.Getwd()
	defer os.Chdir(originalDir)
	os.Chdir(tmpDir)

	// Create app with mock services
	mockAPIClient := &MockAPIClient{
		AnalyzePackagesFunc: func(ctx context.Context, packages []rootio.Package, ignore []rootio.Package, ecosystem string) (*rootio.AnalyzePackagesResponse, error) {
			return &rootio.AnalyzePackagesResponse{
				Patches: []rootio.PackagePatch{
					{
						PackageName: "express",
						Version:     "4.18.0",
						Patch:       rootio.PatchInfo{Name: "express", Version: "4.18.2-root.io.1"},
						PatchAlias:  rootio.PatchInfo{Name: "@rootio/express", Version: "4.18.2-root.io.1"},
					},
				},
			}, nil
		},
	}

	// Create a valid yarn.lock with v1 header
	lockFile := filepath.Join(tmpDir, "yarn.lock")
	yarnLockContent := `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

express@4.18.0:
  version "4.18.0"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.0.tgz"
  integrity sha512-...`
	if err := os.WriteFile(lockFile, []byte(yarnLockContent), 0644); err != nil {
		t.Fatalf("Failed to create lock file: %v", err)
	}

	// Use real YarnParser for package.json updates
	yarnParser := NewYarnParser()

	app := NewAppWithServices(
		"test-key",
		"https://api.root.io",
		"yarn",
		false, // not dry-run
		nil,
		logger,
		yarnParser,
		mockAPIClient,
	)

	// Run the app
	if err := app.Run(ctx); err != nil {
		t.Fatalf("App run failed: %v", err)
	}

	// Read updated package.json
	updatedContent, err := os.ReadFile(packageJSON)
	if err != nil {
		t.Fatalf("Failed to read updated package.json: %v", err)
	}

	// Parse and verify
	var pkgJSON map[string]interface{}
	if err := json.Unmarshal(updatedContent, &pkgJSON); err != nil {
		t.Fatalf("Failed to parse updated package.json: %v", err)
	}

	// express@4.18.0 is the user's direct dep at the vulnerable version,
	// no transitive consumers in the fixture → expect the entry bumped in
	// place, no resolutions field needed.
	deps := pkgJSON["dependencies"].(map[string]interface{})
	expectedVersion := "4.18.2-root.io.1"
	if deps["express"].(string) != expectedVersion {
		t.Errorf("Expected express direct dep bumped to %q, got %q", expectedVersion, deps["express"])
	}

	t.Log("Successfully bumped direct dep in place for yarn (no transitive consumers)")
}

// TestNpmApp_UpdatePackageJSON_Pnpm tests pnpm overrides format (nested under "pnpm")
func TestNpmApp_UpdatePackageJSON_Pnpm(t *testing.T) {
	ctx := context.Background()
	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))

	// Create temp directory
	tmpDir := t.TempDir()

	// Create package.json
	packageJSON := filepath.Join(tmpDir, "package.json")
	initialContent := `{
  "name": "test-project",
  "version": "1.0.0",
  "dependencies": {
    "jest": "29.0.0"
  }
}`
	if err := os.WriteFile(packageJSON, []byte(initialContent), 0644); err != nil {
		t.Fatalf("Failed to create package.json: %v", err)
	}

	// Change to temp directory
	originalDir, _ := os.Getwd()
	defer os.Chdir(originalDir)
	os.Chdir(tmpDir)

	// Create app with mock services
	mockAPIClient := &MockAPIClient{
		AnalyzePackagesFunc: func(ctx context.Context, packages []rootio.Package, ignore []rootio.Package, ecosystem string) (*rootio.AnalyzePackagesResponse, error) {
			return &rootio.AnalyzePackagesResponse{
				Patches: []rootio.PackagePatch{
					{
						PackageName: "jest",
						Version:     "29.0.0",
						Patch:       rootio.PatchInfo{Name: "jest", Version: "29.5.0-root.io.1"},
						PatchAlias:  rootio.PatchInfo{Name: "@rootio/jest", Version: "29.5.0-root.io.1"},
					},
				},
			}, nil
		},
	}

	// Create a fake pnpm-lock.yaml (just needs to exist - pnpm parser not fully implemented)
	lockFile := filepath.Join(tmpDir, "pnpm-lock.yaml")
	if err := os.WriteFile(lockFile, []byte("lockfileVersion: '6.0'\n"), 0644); err != nil {
		t.Fatalf("Failed to create lock file: %v", err)
	}

	// Use MockPnpmParser - mocks Parse but uses real UpdatePackageJSON
	mockPnpmParser := &MockPnpmParser{
		PnpmParser: NewPnpmParser(),
		ParseFunc: func(ctx context.Context, filePath string) ([]common.PackageInfo, error) {
			return []common.PackageInfo{
				{Name: "jest", Version: "29.0.0"},
			}, nil
		},
	}

	app := NewAppWithServices(
		"test-key",
		"https://api.root.io",
		"pnpm",
		false, // not dry-run
		nil,
		logger,
		mockPnpmParser,
		mockAPIClient,
	)

	// Run the app
	if err := app.Run(ctx); err != nil {
		t.Fatalf("App run failed: %v", err)
	}

	// Read updated package.json
	updatedContent, err := os.ReadFile(packageJSON)
	if err != nil {
		t.Fatalf("Failed to read updated package.json: %v", err)
	}

	// Parse and verify
	var pkgJSON map[string]interface{}
	if err := json.Unmarshal(updatedContent, &pkgJSON); err != nil {
		t.Fatalf("Failed to parse updated package.json: %v", err)
	}

	// Verify pnpm field exists
	pnpmConfig, ok := pkgJSON["pnpm"].(map[string]interface{})
	if !ok {
		t.Fatal("Expected 'pnpm' field in package.json for pnpm")
	}

	// Verify overrides nested under pnpm
	overrides, ok := pnpmConfig["overrides"].(map[string]interface{})
	if !ok {
		t.Fatal("Expected 'overrides' field under 'pnpm' in package.json")
	}

	// Verify jest version-scoped override (pnpm uses "<name>@<version>" keys).
	jestOverride, ok := overrides["jest@29.0.0"].(string)
	if !ok {
		t.Fatalf("Expected 'jest@29.0.0' in pnpm.overrides; got: %v", overrides)
	}
	expectedOverride := "29.5.0-root.io.1"
	if jestOverride != expectedOverride {
		t.Errorf("Expected jest override '%s', got '%s'", expectedOverride, jestOverride)
	}

	t.Log("Successfully updated package.json with pnpm overrides (nested under 'pnpm', plain versions)")
}

// TestNpmApp_AddOverrides_NoExistingOverrides tests adding overrides to a package.json without existing overrides
func TestNpmApp_AddOverrides_NoExistingOverrides(t *testing.T) {
	ctx := context.Background()
	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))

	// Create temp directory
	tmpDir := t.TempDir()

	// Create package.json WITHOUT overrides field
	packageJSON := filepath.Join(tmpDir, "package.json")
	initialContent := `{
  "name": "test-project",
  "version": "1.0.0",
  "dependencies": {
    "lodash": "4.17.20",
    "express": "4.18.0"
  }
}`
	if err := os.WriteFile(packageJSON, []byte(initialContent), 0644); err != nil {
		t.Fatalf("Failed to create package.json: %v", err)
	}

	// Change to temp directory
	originalDir, _ := os.Getwd()
	defer os.Chdir(originalDir)
	os.Chdir(tmpDir)

	// Create app with mock services
	mockAPIClient := &MockAPIClient{
		AnalyzePackagesFunc: func(ctx context.Context, packages []rootio.Package, ignore []rootio.Package, ecosystem string) (*rootio.AnalyzePackagesResponse, error) {
			return &rootio.AnalyzePackagesResponse{
				Patches: []rootio.PackagePatch{
					{
						PackageName: "lodash",
						Version:     "4.17.20",
						Patch:       rootio.PatchInfo{Name: "lodash", Version: "4.17.21-root.io.1"},
						PatchAlias:  rootio.PatchInfo{Name: "@rootio/lodash", Version: "4.17.21-root.io.1"},
					},
				},
			}, nil
		},
	}

	// Create a fake lock file
	lockFile := filepath.Join(tmpDir, "package-lock.json")
	lockContent := `{
  "name": "test-project",
  "lockfileVersion": 3,
  "packages": {
    "": {
      "dependencies": { "lodash": "4.17.20", "express": "4.18.0" }
    },
    "node_modules/lodash": {
      "version": "4.17.20"
    },
    "node_modules/express": {
      "version": "4.18.0"
    }
  }
}`
	if err := os.WriteFile(lockFile, []byte(lockContent), 0644); err != nil {
		t.Fatalf("Failed to create lock file: %v", err)
	}

	app := NewAppWithServices(
		"test-key",
		"https://api.root.io",
		"npm",
		false, // not dry-run
		nil,
		logger,
		NewParser(),
		mockAPIClient,
	)

	// Run the app
	if err := app.Run(ctx); err != nil {
		t.Fatalf("App run failed: %v", err)
	}

	// Read updated package.json
	updatedContent, err := os.ReadFile(packageJSON)
	if err != nil {
		t.Fatalf("Failed to read updated package.json: %v", err)
	}

	// Parse and verify
	var pkgJSON map[string]interface{}
	if err := json.Unmarshal(updatedContent, &pkgJSON); err != nil {
		t.Fatalf("Failed to parse updated package.json: %v", err)
	}

	// Dependency entry is bumped in place (no aliasing, no name change), plus
	// a plain version-scoped override for transitive uses.
	deps := pkgJSON["dependencies"].(map[string]interface{})

	expectedVersion := "4.17.21-root.io.1"
	if deps["lodash"] == nil {
		t.Fatal("Expected lodash to remain in dependencies")
	} else if deps["lodash"].(string) != expectedVersion {
		t.Errorf("Expected lodash version %q, got %q", expectedVersion, deps["lodash"])
	}

	// Should have version-scoped override for transitive uses
	overrides, hasOverrides := pkgJSON["overrides"].(map[string]interface{})
	if !hasOverrides {
		t.Error("expected overrides field with version-scoped override")
	}
	if hasOverrides {
		found := false
		for key, val := range overrides {
			if strings.HasPrefix(key, "lodash@") && val == expectedVersion {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("expected plain version-scoped override for lodash in overrides, got %+v", overrides)
		}
	}

	if !strings.Contains(string(updatedContent), "\n") {
		t.Error("Expected formatted JSON with newlines")
	}
	if !strings.Contains(string(updatedContent), "  ") {
		t.Error("Expected indented JSON")
	}

	t.Log("Successfully bumped direct dep in place")
}

// TestNpmApp_AddOverrides_WithExistingOverrides tests appending to existing overrides
func TestNpmApp_AddOverrides_WithExistingOverrides(t *testing.T) {
	ctx := context.Background()
	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))

	// Create temp directory
	tmpDir := t.TempDir()

	// Create package.json WITH existing overrides
	packageJSON := filepath.Join(tmpDir, "package.json")
	initialContent := `{
  "name": "test-project",
  "version": "1.0.0",
  "dependencies": {
    "lodash": "4.17.20",
    "express": "4.18.0",
    "axios": "0.21.1"
  },
  "overrides": {
    "axios": "npm:@rootio/axios@0.21.2-root.io.1"
  }
}`
	if err := os.WriteFile(packageJSON, []byte(initialContent), 0644); err != nil {
		t.Fatalf("Failed to create package.json: %v", err)
	}

	// Change to temp directory
	originalDir, _ := os.Getwd()
	defer os.Chdir(originalDir)
	os.Chdir(tmpDir)

	// Create app with mock services
	mockAPIClient := &MockAPIClient{
		AnalyzePackagesFunc: func(ctx context.Context, packages []rootio.Package, ignore []rootio.Package, ecosystem string) (*rootio.AnalyzePackagesResponse, error) {
			return &rootio.AnalyzePackagesResponse{
				Patches: []rootio.PackagePatch{
					{
						PackageName: "lodash",
						Version:     "4.17.20",
						Patch:       rootio.PatchInfo{Name: "lodash", Version: "4.17.21-root.io.1"},
						PatchAlias:  rootio.PatchInfo{Name: "@rootio/lodash", Version: "4.17.21-root.io.1"},
					},
					{
						PackageName: "express",
						Version:     "4.18.0",
						Patch:       rootio.PatchInfo{Name: "express", Version: "4.18.2-root.io.1"},
						PatchAlias:  rootio.PatchInfo{Name: "@rootio/express", Version: "4.18.2-root.io.1"},
					},
				},
			}, nil
		},
	}

	// Create a fake lock file
	lockFile := filepath.Join(tmpDir, "package-lock.json")
	lockContent := `{
  "name": "test-project",
  "lockfileVersion": 3,
  "packages": {
    "": {
      "dependencies": { "lodash": "4.17.20", "express": "4.18.0", "axios": "0.21.1" }
    },
    "node_modules/lodash": {
      "version": "4.17.20"
    },
    "node_modules/express": {
      "version": "4.18.0"
    },
    "node_modules/axios": {
      "version": "0.21.1"
    }
  }
}`
	if err := os.WriteFile(lockFile, []byte(lockContent), 0644); err != nil {
		t.Fatalf("Failed to create lock file: %v", err)
	}

	app := NewAppWithServices(
		"test-key",
		"https://api.root.io",
		"npm",
		false, // not dry-run
		nil,
		logger,
		NewParser(),
		mockAPIClient,
	)

	// Run the app
	if err := app.Run(ctx); err != nil {
		t.Fatalf("App run failed: %v", err)
	}

	// Read updated package.json
	updatedContent, err := os.ReadFile(packageJSON)
	if err != nil {
		t.Fatalf("Failed to read updated package.json: %v", err)
	}

	// Parse and verify
	var pkgJSON map[string]interface{}
	if err := json.Unmarshal(updatedContent, &pkgJSON); err != nil {
		t.Fatalf("Failed to parse updated package.json: %v", err)
	}

	// Verify overrides field exists and has all three packages
	overrides, ok := pkgJSON["overrides"].(map[string]interface{})
	if !ok {
		t.Fatal("Expected 'overrides' field")
	}

	// Existing axios override is unrelated to the patches; it must be preserved
	// verbatim, alias syntax and all — this test only asserts what the tool
	// itself writes for lodash/express, not pre-existing entries.
	// Both lodash and express are direct + vulnerable, so:
	// - Dependency entries bumped in place (no name change)
	// - Plain version-scoped overrides added for transitive uses
	if axios, _ := overrides["axios"].(string); axios != "npm:@rootio/axios@0.21.2-root.io.1" {
		t.Errorf("existing axios override should be preserved, got %q", axios)
	}

	// Check for version-scoped overrides
	foundLodash := false
	foundExpress := false
	for key, val := range overrides {
		if strings.HasPrefix(key, "lodash@") && val == "4.17.21-root.io.1" {
			foundLodash = true
		}
		if strings.HasPrefix(key, "express@") && val == "4.18.2-root.io.1" {
			foundExpress = true
		}
	}
	if !foundLodash {
		t.Errorf("expected plain version-scoped lodash override, got %+v", overrides)
	}
	if !foundExpress {
		t.Errorf("expected plain version-scoped express override, got %+v", overrides)
	}

	deps := pkgJSON["dependencies"].(map[string]interface{})

	if deps["lodash"] == nil {
		t.Fatal("Expected lodash to remain in dependencies")
	} else if deps["lodash"].(string) != "4.17.21-root.io.1" {
		t.Errorf("Expected lodash version 4.17.21-root.io.1, got %q", deps["lodash"])
	}
	if deps["express"] == nil {
		t.Fatal("Expected express to remain in dependencies")
	} else if deps["express"].(string) != "4.18.2-root.io.1" {
		t.Errorf("Expected express version 4.18.2-root.io.1, got %q", deps["express"])
	}

	t.Log("Successfully bumped direct deps in place and preserved existing unrelated override")
}
