package npm

import (
	"context"
	"encoding/json"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"rootio_patcher/cmd/rootio_patcher/common"
	"rootio_patcher/pkg/rootio"
)

// TestNpmApp_UpdatePackageJSON_Npm tests npm overrides format
func TestNpmApp_UpdatePackageJSON_Npm(t *testing.T) {
	ctx := context.Background()
	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))

	// Create temp directory
	tmpDir := t.TempDir()

	// Create package.json
	packageJSON := filepath.Join(tmpDir, "package.json")
	initialContent := `{
  "name": "test-project",
  "version": "1.0.0",
  "dependencies": {
    "lodash": "4.17.20"
  }
}`
	if err := os.WriteFile(packageJSON, []byte(initialContent), 0644); err != nil {
		t.Fatalf("Failed to create package.json: %v", err)
	}

	// Change to temp directory
	originalDir, _ := os.Getwd()
	defer os.Chdir(originalDir)
	os.Chdir(tmpDir)

	// Create app with mock services
	mockAPIClient := &MockAPIClient{
		AnalyzePackagesFunc: func(ctx context.Context, packages []rootio.Package, ignore []rootio.Package, ecosystem string) (*rootio.AnalyzePackagesResponse, error) {
			return &rootio.AnalyzePackagesResponse{
				Patches: []rootio.PackagePatch{
					{
						PackageName: "lodash",
						Version:     "4.17.20",
						Patch:       rootio.PatchInfo{Name: "lodash", Version: "4.17.21"},
						PatchAlias:  rootio.PatchInfo{Name: "@rootio/lodash", Version: "4.17.21"},
					},
				},
			}, nil
		},
	}

	// Create a fake lock file
	lockFile := filepath.Join(tmpDir, "package-lock.json")
	lockContent := `{
  "name": "test-project",
  "lockfileVersion": 3,
  "packages": {
    "": {
      "dependencies": { "lodash": "4.17.20" }
    },
    "node_modules/lodash": {
      "version": "4.17.20"
    }
  }
}`
	if err := os.WriteFile(lockFile, []byte(lockContent), 0644); err != nil {
		t.Fatalf("Failed to create lock file: %v", err)
	}

	app := NewAppWithServices(
		"test-key",
		"https://api.root.io",
		"https://pkg.root.io",
		"npm",
		false, // not dry-run
		true,  // useAlias (default)
		nil,
		logger,
		NewParser(),
		mockAPIClient,
		&MockCommandRunner{},
	)

	// Run the app
	if err := app.Run(ctx); err != nil {
		t.Fatalf("App run failed: %v", err)
	}

	// Read updated package.json
	updatedContent, err := os.ReadFile(packageJSON)
	if err != nil {
		t.Fatalf("Failed to read updated package.json: %v", err)
	}

	// Parse and verify
	var pkgJSON map[string]interface{}
	if err := json.Unmarshal(updatedContent, &pkgJSON); err != nil {
		t.Fatalf("Failed to parse updated package.json: %v", err)
	}

	// lodash@4.17.20 is the user's direct dep AT the vulnerable version, no transitive
	// consumer. The dependency VALUE is rewritten to the npm: alias; key kept, no rename.
	deps := pkgJSON["dependencies"].(map[string]interface{})

	expectedAlias := "npm:@rootio/lodash@4.17.21"
	if v, _ := deps["lodash"].(string); v != expectedAlias {
		t.Errorf("Expected lodash rewritten to %q, got %q", expectedAlias, deps["lodash"])
	}
	if _, exists := deps["@rootio/lodash"]; exists {
		t.Error("direct dep key must not be renamed to @rootio/lodash")
	}

	t.Log("Successfully rewrote direct dep to npm: alias for npm (no transitive consumers)")
}

// TestNpmApp_UpdatePackageJSON_Yarn tests yarn resolutions format
func TestNpmApp_UpdatePackageJSON_Yarn(t *testing.T) {
	ctx := context.Background()
	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))

	// Create temp directory
	tmpDir := t.TempDir()

	// Create package.json
	packageJSON := filepath.Join(tmpDir, "package.json")
	initialContent := `{
  "name": "test-project",
  "version": "1.0.0",
  "dependencies": {
    "express": "4.18.0"
  }
}`
	if err := os.WriteFile(packageJSON, []byte(initialContent), 0644); err != nil {
		t.Fatalf("Failed to create package.json: %v", err)
	}

	// Change to temp directory
	originalDir, _ := os.Getwd()
	defer os.Chdir(originalDir)
	os.Chdir(tmpDir)

	// Create app with mock services
	mockAPIClient := &MockAPIClient{
		AnalyzePackagesFunc: func(ctx context.Context, packages []rootio.Package, ignore []rootio.Package, ecosystem string) (*rootio.AnalyzePackagesResponse, error) {
			return &rootio.AnalyzePackagesResponse{
				Patches: []rootio.PackagePatch{
					{
						PackageName: "express",
						Version:     "4.18.0",
						Patch:       rootio.PatchInfo{Name: "express", Version: "4.18.2"},
						PatchAlias:  rootio.PatchInfo{Name: "@rootio/express", Version: "4.18.2"},
					},
				},
			}, nil
		},
	}

	// Create a valid yarn.lock with v1 header
	lockFile := filepath.Join(tmpDir, "yarn.lock")
	yarnLockContent := `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

express@4.18.0:
  version "4.18.0"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.0.tgz"
  integrity sha512-...`
	if err := os.WriteFile(lockFile, []byte(yarnLockContent), 0644); err != nil {
		t.Fatalf("Failed to create lock file: %v", err)
	}

	// Use real YarnParser for package.json updates
	yarnParser := NewYarnParser()

	app := NewAppWithServices(
		"test-key",
		"https://api.root.io",
		"https://pkg.root.io",
		"yarn",
		false, // not dry-run
		true,  // useAlias (default)
		nil,
		logger,
		yarnParser,
		mockAPIClient,
		&MockCommandRunner{},
	)

	// Run the app
	if err := app.Run(ctx); err != nil {
		t.Fatalf("App run failed: %v", err)
	}

	// Read updated package.json
	updatedContent, err := os.ReadFile(packageJSON)
	if err != nil {
		t.Fatalf("Failed to read updated package.json: %v", err)
	}

	// Parse and verify
	var pkgJSON map[string]interface{}
	if err := json.Unmarshal(updatedContent, &pkgJSON); err != nil {
		t.Fatalf("Failed to parse updated package.json: %v", err)
	}

	// express@4.18.0 is the user's direct dep at the vulnerable version,
	// no transitive consumers in the fixture → expect direct rewrite, no
	// resolutions field needed.
	deps := pkgJSON["dependencies"].(map[string]interface{})
	expectedAlias := "npm:@rootio/express@4.18.2"
	if deps["express"].(string) != expectedAlias {
		t.Errorf("Expected express direct dep rewritten to %q, got %q", expectedAlias, deps["express"])
	}

	t.Log("Successfully rewrote direct dep to alias for yarn (no transitive consumers)")
}

// TestNpmApp_UpdatePackageJSON_Pnpm tests pnpm overrides format (nested under "pnpm")
func TestNpmApp_UpdatePackageJSON_Pnpm(t *testing.T) {
	ctx := context.Background()
	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))

	// Create temp directory
	tmpDir := t.TempDir()

	// Create package.json
	packageJSON := filepath.Join(tmpDir, "package.json")
	initialContent := `{
  "name": "test-project",
  "version": "1.0.0",
  "dependencies": {
    "jest": "29.0.0"
  }
}`
	if err := os.WriteFile(packageJSON, []byte(initialContent), 0644); err != nil {
		t.Fatalf("Failed to create package.json: %v", err)
	}

	// Change to temp directory
	originalDir, _ := os.Getwd()
	defer os.Chdir(originalDir)
	os.Chdir(tmpDir)

	// Create app with mock services
	mockAPIClient := &MockAPIClient{
		AnalyzePackagesFunc: func(ctx context.Context, packages []rootio.Package, ignore []rootio.Package, ecosystem string) (*rootio.AnalyzePackagesResponse, error) {
			return &rootio.AnalyzePackagesResponse{
				Patches: []rootio.PackagePatch{
					{
						PackageName: "jest",
						Version:     "29.0.0",
						Patch:       rootio.PatchInfo{Name: "jest", Version: "29.5.0"},
						PatchAlias:  rootio.PatchInfo{Name: "@rootio/jest", Version: "29.5.0"},
					},
				},
			}, nil
		},
	}

	// Create a fake pnpm-lock.yaml (just needs to exist - pnpm parser not fully implemented)
	lockFile := filepath.Join(tmpDir, "pnpm-lock.yaml")
	if err := os.WriteFile(lockFile, []byte("lockfileVersion: '6.0'\n"), 0644); err != nil {
		t.Fatalf("Failed to create lock file: %v", err)
	}

	// Use MockPnpmParser - mocks Parse but uses real UpdatePackageJSON
	mockPnpmParser := &MockPnpmParser{
		PnpmParser: NewPnpmParser(),
		ParseFunc: func(ctx context.Context, filePath string) ([]common.PackageInfo, error) {
			return []common.PackageInfo{
				{Name: "jest", Version: "29.0.0"},
			}, nil
		},
	}

	app := NewAppWithServices(
		"test-key",
		"https://api.root.io",
		"https://pkg.root.io",
		"pnpm",
		false, // not dry-run
		true,  // useAlias (default)
		nil,
		logger,
		mockPnpmParser,
		mockAPIClient,
		&MockCommandRunner{},
	)

	// Run the app
	if err := app.Run(ctx); err != nil {
		t.Fatalf("App run failed: %v", err)
	}

	// Read updated package.json
	updatedContent, err := os.ReadFile(packageJSON)
	if err != nil {
		t.Fatalf("Failed to read updated package.json: %v", err)
	}

	// Parse and verify
	var pkgJSON map[string]interface{}
	if err := json.Unmarshal(updatedContent, &pkgJSON); err != nil {
		t.Fatalf("Failed to parse updated package.json: %v", err)
	}

	// Verify pnpm field exists
	pnpmConfig, ok := pkgJSON["pnpm"].(map[string]interface{})
	if !ok {
		t.Fatal("Expected 'pnpm' field in package.json for pnpm")
	}

	// Verify overrides nested under pnpm
	overrides, ok := pnpmConfig["overrides"].(map[string]interface{})
	if !ok {
		t.Fatal("Expected 'overrides' field under 'pnpm' in package.json")
	}

	// Verify jest version-scoped override (pnpm uses "<name>@<version>" keys).
	jestOverride, ok := overrides["jest@29.0.0"].(string)
	if !ok {
		t.Fatalf("Expected 'jest@29.0.0' in pnpm.overrides; got: %v", overrides)
	}
	expectedOverride := "npm:@rootio/jest@29.5.0"
	if jestOverride != expectedOverride {
		t.Errorf("Expected jest override '%s', got '%s'", expectedOverride, jestOverride)
	}

	t.Log("Successfully updated package.json with pnpm overrides (nested under 'pnpm', aliased packages)")
}

// TestNpmApp_AddOverrides_NoExistingOverrides tests adding overrides to a package.json without existing overrides
func TestNpmApp_AddOverrides_NoExistingOverrides(t *testing.T) {
	ctx := context.Background()
	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))

	// Create temp directory
	tmpDir := t.TempDir()

	// Create package.json WITHOUT overrides field
	packageJSON := filepath.Join(tmpDir, "package.json")
	initialContent := `{
  "name": "test-project",
  "version": "1.0.0",
  "dependencies": {
    "lodash": "4.17.20",
    "express": "4.18.0"
  }
}`
	if err := os.WriteFile(packageJSON, []byte(initialContent), 0644); err != nil {
		t.Fatalf("Failed to create package.json: %v", err)
	}

	// Change to temp directory
	originalDir, _ := os.Getwd()
	defer os.Chdir(originalDir)
	os.Chdir(tmpDir)

	// Create app with mock services
	mockAPIClient := &MockAPIClient{
		AnalyzePackagesFunc: func(ctx context.Context, packages []rootio.Package, ignore []rootio.Package, ecosystem string) (*rootio.AnalyzePackagesResponse, error) {
			return &rootio.AnalyzePackagesResponse{
				Patches: []rootio.PackagePatch{
					{
						PackageName: "lodash",
						Version:     "4.17.20",
						Patch:       rootio.PatchInfo{Name: "lodash", Version: "4.17.21"},
						PatchAlias:  rootio.PatchInfo{Name: "@rootio/lodash", Version: "4.17.21"},
					},
				},
			}, nil
		},
	}

	// Create a fake lock file
	lockFile := filepath.Join(tmpDir, "package-lock.json")
	lockContent := `{
  "name": "test-project",
  "lockfileVersion": 3,
  "packages": {
    "": {
      "dependencies": { "lodash": "4.17.20", "express": "4.18.0" }
    },
    "node_modules/lodash": {
      "version": "4.17.20"
    },
    "node_modules/express": {
      "version": "4.18.0"
    }
  }
}`
	if err := os.WriteFile(lockFile, []byte(lockContent), 0644); err != nil {
		t.Fatalf("Failed to create lock file: %v", err)
	}

	app := NewAppWithServices(
		"test-key",
		"https://api.root.io",
		"https://pkg.root.io",
		"npm",
		false, // not dry-run
		true,  // useAlias (default)
		nil,
		logger,
		NewParser(),
		mockAPIClient,
		&MockCommandRunner{},
	)

	// Run the app
	if err := app.Run(ctx); err != nil {
		t.Fatalf("App run failed: %v", err)
	}

	// Read updated package.json
	updatedContent, err := os.ReadFile(packageJSON)
	if err != nil {
		t.Fatalf("Failed to read updated package.json: %v", err)
	}

	// Parse and verify
	var pkgJSON map[string]interface{}
	if err := json.Unmarshal(updatedContent, &pkgJSON); err != nil {
		t.Fatalf("Failed to parse updated package.json: %v", err)
	}

	// Direct-dep rewrite: the "lodash" key is KEPT, its value becomes the npm: alias.
	// (Only form npm can resolve for a -root.io build; no key rename, no stray override.)
	deps := pkgJSON["dependencies"].(map[string]interface{})

	expectedAlias := "npm:@rootio/lodash@4.17.21"
	if deps["lodash"] == nil {
		t.Error("Expected lodash key to remain in dependencies (rewritten to npm: alias)")
	} else if deps["lodash"].(string) != expectedAlias {
		t.Errorf("Expected lodash rewritten to %q, got %q", expectedAlias, deps["lodash"])
	}
	// Key must NOT be renamed to @rootio/lodash.
	if _, exists := deps["@rootio/lodash"]; exists {
		t.Error("Direct dep key must not be renamed to @rootio/lodash")
	}
	// A direct dep must NOT also get an overrides entry (EOVERRIDE).
	if overrides, hasOverrides := pkgJSON["overrides"].(map[string]interface{}); hasOverrides {
		for key := range overrides {
			if strings.HasPrefix(key, "lodash@") {
				t.Errorf("direct dep must not also get an overrides entry, found %q", key)
			}
		}
	}

	if !strings.Contains(string(updatedContent), "\n") {
		t.Error("Expected formatted JSON with newlines")
	}
	if !strings.Contains(string(updatedContent), "  ") {
		t.Error("Expected indented JSON")
	}

	t.Log("Successfully rewrote direct dep to @rootio npm: alias")
}

// TestNpmApp_AddOverrides_WithExistingOverrides tests appending to existing overrides
func TestNpmApp_AddOverrides_WithExistingOverrides(t *testing.T) {
	ctx := context.Background()
	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))

	// Create temp directory
	tmpDir := t.TempDir()

	// Create package.json WITH existing overrides
	packageJSON := filepath.Join(tmpDir, "package.json")
	initialContent := `{
  "name": "test-project",
  "version": "1.0.0",
  "dependencies": {
    "lodash": "4.17.20",
    "express": "4.18.0",
    "axios": "0.21.1"
  },
  "overrides": {
    "axios": "npm:@rootio/axios@0.21.2"
  }
}`
	if err := os.WriteFile(packageJSON, []byte(initialContent), 0644); err != nil {
		t.Fatalf("Failed to create package.json: %v", err)
	}

	// Change to temp directory
	originalDir, _ := os.Getwd()
	defer os.Chdir(originalDir)
	os.Chdir(tmpDir)

	// Create app with mock services
	mockAPIClient := &MockAPIClient{
		AnalyzePackagesFunc: func(ctx context.Context, packages []rootio.Package, ignore []rootio.Package, ecosystem string) (*rootio.AnalyzePackagesResponse, error) {
			return &rootio.AnalyzePackagesResponse{
				Patches: []rootio.PackagePatch{
					{
						PackageName: "lodash",
						Version:     "4.17.20",
						Patch:       rootio.PatchInfo{Name: "lodash", Version: "4.17.21"},
						PatchAlias:  rootio.PatchInfo{Name: "@rootio/lodash", Version: "4.17.21"},
					},
					{
						PackageName: "express",
						Version:     "4.18.0",
						Patch:       rootio.PatchInfo{Name: "express", Version: "4.18.2"},
						PatchAlias:  rootio.PatchInfo{Name: "@rootio/express", Version: "4.18.2"},
					},
				},
			}, nil
		},
	}

	// Create a fake lock file
	lockFile := filepath.Join(tmpDir, "package-lock.json")
	lockContent := `{
  "name": "test-project",
  "lockfileVersion": 3,
  "packages": {
    "": {
      "dependencies": { "lodash": "4.17.20", "express": "4.18.0", "axios": "0.21.1" }
    },
    "node_modules/lodash": {
      "version": "4.17.20"
    },
    "node_modules/express": {
      "version": "4.18.0"
    },
    "node_modules/axios": {
      "version": "0.21.1"
    }
  }
}`
	if err := os.WriteFile(lockFile, []byte(lockContent), 0644); err != nil {
		t.Fatalf("Failed to create lock file: %v", err)
	}

	app := NewAppWithServices(
		"test-key",
		"https://api.root.io",
		"https://pkg.root.io",
		"npm",
		false, // not dry-run
		true,  // useAlias (default)
		nil,
		logger,
		NewParser(),
		mockAPIClient,
		&MockCommandRunner{},
	)

	// Run the app
	if err := app.Run(ctx); err != nil {
		t.Fatalf("App run failed: %v", err)
	}

	// Read updated package.json
	updatedContent, err := os.ReadFile(packageJSON)
	if err != nil {
		t.Fatalf("Failed to read updated package.json: %v", err)
	}

	// Parse and verify
	var pkgJSON map[string]interface{}
	if err := json.Unmarshal(updatedContent, &pkgJSON); err != nil {
		t.Fatalf("Failed to parse updated package.json: %v", err)
	}

	// Verify overrides field exists (it still holds the pre-existing axios override)
	overrides, ok := pkgJSON["overrides"].(map[string]interface{})
	if !ok {
		t.Fatal("Expected 'overrides' field")
	}

	// Existing axios override is unrelated to the patches; it must be preserved.
	// Both lodash and express are direct + vulnerable, so each dependency VALUE is
	// rewritten to the npm: alias (key kept), and NO overrides entry is emitted for them.
	if axios, _ := overrides["axios"].(string); axios != "npm:@rootio/axios@0.21.2" {
		t.Errorf("existing axios override should be preserved, got %q", axios)
	}

	// Direct deps must NOT get overrides entries (would cause EOVERRIDE).
	for key := range overrides {
		if strings.HasPrefix(key, "lodash@") || strings.HasPrefix(key, "express@") {
			t.Errorf("direct dep must not get an overrides entry, found %q", key)
		}
	}

	deps := pkgJSON["dependencies"].(map[string]interface{})

	// Keys kept, values rewritten to the npm: alias.
	if v, _ := deps["lodash"].(string); v != "npm:@rootio/lodash@4.17.21" {
		t.Errorf("Expected lodash rewritten to npm:@rootio/lodash@4.17.21, got %q", deps["lodash"])
	}
	if v, _ := deps["express"].(string); v != "npm:@rootio/express@4.18.2" {
		t.Errorf("Expected express rewritten to npm:@rootio/express@4.18.2, got %q", deps["express"])
	}
	// Keys must NOT be renamed to the scoped names.
	if _, exists := deps["@rootio/lodash"]; exists {
		t.Error("lodash key must not be renamed to @rootio/lodash")
	}
	if _, exists := deps["@rootio/express"]; exists {
		t.Error("express key must not be renamed to @rootio/express")
	}

	t.Log("Successfully rewrote direct deps to npm: aliases and preserved existing unrelated override")
}
